name = "my-worker"
main = "src/index.js" # Adjust this path to match your file structure
compatibility_date = "2023-10-30"

[vars]
DODO_PAYMENTS_WEBHOOK_KEY = "whsec_d8zgtcnNkRh9HHpKqMV++i0bJpUqGfY+"
DODO_PAYMENTS_ENVIRONMENT = "test_mode"
DODO_PAYMENTS_API_KEY= "7t-SFMf1FUp7psLG.TYE8AdlXLjhpNpUrTijp00LSwHwEmcqcCSU3_mAQ7mWAuB5p"
DODO_PAYMENTS_RETURN_URL= "https://demo1.imaginea.store/success"
command = "npm install"

pages_build_output_dir = "src"

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "d470cbd8ccd24330a5c4e0492317cacd"      # Production ID
preview_id = "b48dca5293744796a838aaf34039e7bf"  # Preview ID